apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: testevents-trigger0
spec:
  broker: default
  filter:
    attributes:
      type: dev.knative.sources.ping
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: broker-display
