apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: my-kafka-channel
spec:
  provisioner:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: ClusterChannelProvisioner
    name: kafka
